version: "3.8"
services:
  app:
    image: kafka-cass-practise:${COMMIT_HASH}
    depends_on: 
      - cass
      - kafka
    environment:
      - CASSANDRA_HOST=cass
      - KAFKA_HOST=kafka
    restart: always

  cass:
    image: cassandra:4.0
    volumes:
      - ./data:/var/lib/cassandra

  cassui:
    image: ipushc/cassandra-web
    environment:
    - CASSANDRA_HOST=cass
    ports:
      - "8083:8083"
    depends_on: 
      - cass
    restart: always
    
  kafka: 
    image: landoop/fast-data-dev
    ports:
      - "3030:3030"
    environment: 
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092