version: "3.8"
services:
  app:
    build: .
    depends_on: 
      - cass
    environment:
      - CASSANDRA_HOST=cass
    restart: always

  cass:
    image: cassandra:4.0
    volumes:
      - ./data:/var/lib/cassandra

  cassui:
    image: ipushc/cassandra-web
    environment:
    - CASSANDRA_HOST=cass
    ports:
      - "8083:8083"
    depends_on: 
      - cass
    restart: always
    
  kafka: 
    image: landoop/fast-data-dev
    ports:
      - "3030:3030"